version: 2
jobs:
  build_and_deploy:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run:
          name: Set environment variables
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=bible-blast' >> $BASH_ENV
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build API project
          command: |
            dotnet restore ./BibleBlast.API/BibleBlast.API.csproj
            dotnet build ./BibleBlast.API/BibleBlast.API.csproj -c Release --no-restore
            dotnet test ./BibleBlast.API.UnitTests/BibleBlast.API.UnitTests.csproj
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.09.2"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build and push Docker image
          command: |
            docker build -t jittles/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push jittles/$IMAGE_NAME:$TAG
      - run:
          name: Deploy app to Digital Ocean Server via Docker
          command: |
            ssh -o StrictHostKeyChecking=no root@134.209.79.190 "/bin/bash ./deploy_app.sh jittles/$IMAGE_NAME:$TAG"