version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run:
          name: Set environment variables
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=bible-blast' >> $BASH_ENV
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t jittles/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push jittles/$IMAGE_NAME:$TAG
      # - run:
      #     name: Deploy app to Digital Ocean Server via Docker
      #     command: |
      #       ssh -o StrictHostKeyChecking=no root@206.189.197.217 "/bin/bash ./deploy_app.sh jittles/$IMAGE_NAME:$TAG"