<%@ Page Language="VB" MasterPageFile="~/MasterPage.master" AutoEventWireup="false" CodeFile="EditQuestions.aspx.vb" Inherits="EditQuestions" title="Untitled Page" %>
<%@ Register src="Controls/CategoryQuestionsByKid.ascx" tagname="CategoryQuestionsByKid" tagprefix="uc1" %>

<%-- Add content controls here --%><asp:Content ID="Content1" runat="server" 
    contentplaceholderid="ContentPlaceHolder2">
    <div>
    
                <asp:SqlDataSource ID="dsCategory" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:BBData %>" 
                    OldValuesParameterFormatString="original_{0}" 
                    SelectCommand="SELECT * FROM [Categories]" 
            DeleteCommand="DELETE FROM [Categories] WHERE [CategoryID] = @original_CategoryID" 
            InsertCommand="INSERT INTO [Categories] ([Name]) VALUES (@Name)" 
            UpdateCommand="UPDATE [Categories] SET [Name] = @Name WHERE [CategoryID] = @original_CategoryID">
                    <DeleteParameters>
                        <asp:Parameter Name="original_CategoryID" Type="Int32" />
                    </DeleteParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="Name" Type="String" />
                        <asp:Parameter Name="original_CategoryID" Type="Int32" />
                    </UpdateParameters>
                    <InsertParameters>
                        <asp:Parameter Name="Name" Type="String" />
                    </InsertParameters>
                </asp:SqlDataSource>
                <asp:SqlDataSource ID="dsQuestion" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:BBData %>" 
                    DeleteCommand="DELETE FROM [Questions] WHERE [QuestionID] = @QuestionID" 
                    InsertCommand="INSERT INTO [Questions] ([CategoryID], [Title], [Description], [Points]) VALUES (@CategoryID, @Title, @Description, @Points)" 
                    SelectCommand="SELECT * FROM [Questions] WHERE ([CategoryID] = @CategoryID)" 
                    
            
            UpdateCommand="UPDATE [Questions] SET [Title] = @Title, [Description] = @Description, [Points] = @Points WHERE [QuestionID] = @QuestionID">
                    <SelectParameters>
                        <asp:ControlParameter ControlID="GridView2" Name="CategoryID" 
                            PropertyName="SelectedValue" Type="Int32" />
                    </SelectParameters>
                    <DeleteParameters>
                        <asp:Parameter Name="QuestionID" Type="Int32" />
                    </DeleteParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="CategoryID" Type="Int32" />
                        <asp:Parameter Name="Title" Type="String" />
                        <asp:Parameter Name="Description" Type="String" />
                        <asp:Parameter Name="Points" Type="Byte" />
                        <asp:Parameter Name="QuestionID" Type="Int32" />
                    </UpdateParameters>
                    <InsertParameters>
                        <asp:ControlParameter ControlID="GridView2" Name="CategoryID" 
                            PropertyName="SelectedValue" Type="Int32" />
                        <asp:Parameter Name="Title" Type="String" />
                        <asp:Parameter Name="Description" Type="String" />
                        <asp:Parameter Name="Points" Type="Byte" />
                    </InsertParameters>
                </asp:SqlDataSource>
                <div style="float: left;">
                <asp:Button ID="btnNewKid0" runat="server" Text="Open 'New Category' Form" />
                <asp:DetailsView ID="DetailsView1" runat="server" DataSourceID="dsCategory" 
                    AllowPaging="True" AutoGenerateRows="False" CellPadding="4" 
                    ForeColor="#333333" GridLines="None" AutoGenerateDeleteButton="True" 
                    AutoGenerateEditButton="True" AutoGenerateInsertButton="True" 
                        EnablePagingCallbacks="True" DataKeyNames="CategoryID" 
                        DefaultMode="Insert" Visible="False">
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <CommandRowStyle BackColor="#E2DED6" Font-Bold="True" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <FieldHeaderStyle BackColor="#E9ECF1" Font-Bold="True" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <Fields>
                        <asp:BoundField DataField="Name" HeaderText="Category" SortExpression="Name" />
                    </Fields>
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <EditRowStyle BackColor="#999999" />
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                </asp:DetailsView>
                    <asp:GridView ID="GridView2" runat="server" AllowSorting="True" 
                        AutoGenerateColumns="False" CellPadding="4" DataKeyNames="CategoryID" 
                        DataSourceID="dsCategory" ForeColor="#333333" GridLines="None">
                        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                        <Columns>
                            <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" 
                                ShowSelectButton="True" />
                            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                        </Columns>
                        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                        <EditRowStyle BackColor="#999999" />
                        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                    </asp:GridView>
                </div>
                <div style="float: right;">
                <asp:Button ID="btnNewKid" runat="server" Text="Open 'New Question' Form" />
                <asp:DetailsView ID="DetailsView2" runat="server" 
                    AutoGenerateRows="False" CellPadding="4" DataSourceID="dsQuestion" 
                    ForeColor="#333333" GridLines="None" EnablePagingCallbacks="True" 
                    AutoGenerateInsertButton="True" DefaultMode="Insert" 
                    Visible="False" DataKeyNames="QuestionID">
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <CommandRowStyle BackColor="#E2DED6" Font-Bold="True" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <FieldHeaderStyle BackColor="#E9ECF1" Font-Bold="True" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <Fields>
                        <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
                        <asp:BoundField DataField="Description" HeaderText="Description" 
                            SortExpression="Description" />
                        <asp:BoundField DataField="Points" HeaderText="Points" 
                            SortExpression="Points" />
                    </Fields>
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <EditRowStyle BackColor="#999999" />
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                </asp:DetailsView>
                    <asp:GridView ID="GridView1" runat="server" AllowSorting="True" 
                    AutoGenerateColumns="False" DataSourceID="dsQuestion" 
                    CellPadding="4" ForeColor="#333333" GridLines="None" 
                    DataKeyNames="QuestionID">
                        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <RowStyle BackColor="#EFF3FB" />
                        <Columns>
                            <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" />
                            <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
                            <asp:BoundField DataField="Description" HeaderText="Description" 
                                SortExpression="Description" />
                            <asp:BoundField DataField="Points" HeaderText="Points" 
                                SortExpression="Points" />
                        </Columns>
                        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <EditRowStyle BackColor="#2461BF" />
                        <AlternatingRowStyle BackColor="White" />
                    </asp:GridView>
                </div>
        <br />
    </div>
</asp:Content>
<asp:Content ID="Content2" runat="server" 
    contentplaceholderid="ContentPlaceHolder1">

                        Edit Questions
</asp:Content>

